services:
  application:
    restart: unless-stopped
    expose:
      - 3000
    build:
      context: .
    env_file:
      - .env

  reverse-proxy:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:8080/tcp
      - 443:8443/tcp
    environment:
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - ENVSUBST_VARS=CERTBOT_DOMAIN
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/user.conf.d/nginx.conf:ro
    depends_on:
      - application

volumes:
  letsencrypt:
