version: '3'

services:
  caddy:
    build:
      context: .
    restart:
      unless-stopped
      # environment:
    #   - SERVER_NAME=${SERVER_NAME:-localhost}
    ports:
      - '3000:80'
        # - '443:443'
      # - '443:443/udp'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-tier

networks:
  app-tier:

volumes:
  caddy_data:
  caddy_config:
