version: '3'

services:
  caddy:
    build:
      context: .
    restart: unless-stopped
    ports:
      - '3000:80'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-tier

networks:
  app-tier:

volumes:
  caddy_data:
  caddy_config:
