/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoImportShowcase: typeof import('./components/AutoImportShowcase.vue')['default']
    TailwindDemo: typeof import('./components/TailwindDemo.vue')['default']
  }
}
